// Preset Campaign Templates for 1-Click Setup

export const PRESET_CAMPAIGNS = {
  gate_cs: {
    id: "gate_cs",
    name: "GATE Computer Science 2027 Arc",
    description: "Complete preparation campaign for GATE CS & IT including Math, Core CS, DPPs, Practice Questions, and PYQs.",
    subjects: [
      {
        id: "subj_math",
        name: "Engineering Mathematics & Aptitude",
        category: "Mathematics",
        color: "from-blue-600 to-indigo-600",
        icon: "Calculator",
        totalLectures: 25,
        completedLectures: 0,
        totalDpps: 20,
        completedDpps: 0,
        targetQuestions: 200,
        completedQuestions: 0,
        targetPyqs: 100,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "Linear Algebra, Calculus, Probability, Discrete Math"
      },
      {
        id: "subj_ds_algo",
        name: "Data Structures & Algorithms",
        category: "Core CS",
        color: "from-emerald-500 to-teal-700",
        icon: "Code",
        totalLectures: 35,
        completedLectures: 0,
        totalDpps: 25,
        completedDpps: 0,
        targetQuestions: 300,
        completedQuestions: 0,
        targetPyqs: 150,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "Trees, Graphs, Dynamic Programming, Sorting, Hash tables"
      },
      {
        id: "subj_os",
        name: "Operating Systems",
        category: "Systems",
        color: "from-violet-600 to-purple-800",
        icon: "Cpu",
        totalLectures: 24,
        completedLectures: 0,
        totalDpps: 18,
        completedDpps: 0,
        targetQuestions: 180,
        completedQuestions: 0,
        targetPyqs: 100,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "Process Synchronization, Deadlocks, Memory Management, File Systems"
      },
      {
        id: "subj_dbms",
        name: "Database Management Systems",
        category: "Systems",
        color: "from-amber-500 to-orange-600",
        icon: "Database",
        totalLectures: 20,
        completedLectures: 0,
        totalDpps: 16,
        completedDpps: 0,
        targetQuestions: 150,
        completedQuestions: 0,
        targetPyqs: 80,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "ER Diagrams, Relational Algebra, SQL, Normalization, Transactions"
      },
      {
        id: "subj_cn",
        name: "Computer Networks",
        category: "Systems",
        color: "from-cyan-500 to-blue-700",
        icon: "Network",
        totalLectures: 22,
        completedLectures: 0,
        totalDpps: 18,
        completedDpps: 0,
        targetQuestions: 160,
        completedQuestions: 0,
        targetPyqs: 90,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "OSI Layers, IP Addressing, TCP/UDP, Flow Control, Routing"
      },
      {
        id: "subj_toc_compiler",
        name: "Theory of Computation & Compilers",
        category: "Theoretical CS",
        color: "from-rose-500 to-red-700",
        icon: "Binary",
        totalLectures: 28,
        completedLectures: 0,
        totalDpps: 22,
        completedDpps: 0,
        targetQuestions: 200,
        completedQuestions: 0,
        targetPyqs: 110,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "DFA/NFA, Context-Free Grammars, Turing Machines, Parsing, Syntax Trees"
      },
      {
        id: "subj_coa",
        name: "Computer Organization & Architecture",
        category: "Hardware",
        color: "from-fuchsia-600 to-pink-800",
        icon: "HardDrive",
        totalLectures: 20,
        completedLectures: 0,
        totalDpps: 15,
        completedDpps: 0,
        targetQuestions: 150,
        completedQuestions: 0,
        targetPyqs: 80,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "Pipelining, Cache Memory, Machine Instructions, ALU, Addressing Modes"
      }
    ]
  },
  fullstack: {
    id: "fullstack",
    name: "Full-Stack Software Engineer Arc",
    description: "Master Modern Web Development, System Design, and Frontend/Backend mastery.",
    subjects: [
      {
        id: "fs_frontend",
        name: "React, Next.js & Modern UI",
        category: "Frontend",
        color: "from-cyan-500 to-blue-600",
        icon: "Layout",
        totalLectures: 30,
        completedLectures: 0,
        totalDpps: 20,
        completedDpps: 0,
        targetQuestions: 100,
        completedQuestions: 0,
        targetPyqs: 50,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "Hooks, State Management, SSR, Styling, Performance"
      },
      {
        id: "fs_backend",
        name: "Node.js, Express & Microservices",
        category: "Backend",
        color: "from-emerald-600 to-green-800",
        icon: "Server",
        totalLectures: 25,
        completedLectures: 0,
        totalDpps: 15,
        completedDpps: 0,
        targetQuestions: 80,
        completedQuestions: 0,
        targetPyqs: 40,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "REST APIs, GraphQL, Authentication, Caching, Event Loops"
      },
      {
        id: "fs_sysdesign",
        name: "System Design & Distributed Systems",
        category: "Architecture",
        color: "from-purple-600 to-indigo-800",
        icon: "Layers",
        totalLectures: 20,
        completedLectures: 0,
        totalDpps: 12,
        completedDpps: 0,
        targetQuestions: 60,
        completedQuestions: 0,
        targetPyqs: 30,
        completedPyqs: 0,
        completedRevisions: 0,
        notes: "Load Balancing, Sharding, Message Queues, CAP Theorem"
      }
    ]
  },
  custom: {
    id: "custom",
    name: "Custom Hero Arc",
    description: "Build your own personalized set of subjects and goals from scratch.",
    subjects: []
  }
};
